Update bot.yml

diff --git a/.github/workflows/bot.yml b/.github/workflows/bot.yml
--- a/.github/workflows/bot.yml
+++ b/.github/workflows/bot.yml
@@ -2,7 +2,6 @@ name: Loc Binh News Bot
 
 on:
   workflow_dispatch:
-
   schedule:
     - cron: "*/5 * * * *"
     - cron: "0 0 * * *"
@@ -10,40 +9,46 @@ on:
 permissions:
   contents: write
 
-concurrency:
-  group: loc-binh-news
-  cancel-in-progress: false
-
 jobs:
   run-bot:
     runs-on: ubuntu-latest
+    timeout-minutes: 5
 
     steps:
-
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Setup Python
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v6
         with:
           python-version: "3.12"
 
       - name: Install libraries
         run: |
+          python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - - name: Chạy bot
-  env:
-    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-  run: python bot.py
+      - name: Check Telegram Token
+        env:
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+        run: |
+          if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
+            echo "ERROR: TELEGRAM_BOT_TOKEN is missing"
+            exit 1
+          fi
+          echo "Telegram Token OK"
 
-      - name: Save bot data
+      - name: Run Bot
+        env:
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+          DAILY_NEWS: ${{ github.event.schedule == '0 0 * * *' && '1' || '0' }}
+        run: |
+          python bot.py
+
+      - name: Save Bot Data
         run: |
           git config user.name "loc-binh-news-bot"
           git config user.email "bot@users.noreply.github.com"
-
-          git add subscribers.json last_update_id.txt
-
+          git add .
           git diff --cached --quiet || git commit -m "Update bot data"
-
           git push
